In [1]:
list(randn(8))

NameError: name 'randn' is not defined

In [2]:
import numpy as np
from numpy.Random import randn

ModuleNotFoundError: No module named 'numpy.Random'

In [3]:
import numpy as np
from numpy.random import randn

In [5]:
list(randn(8))

[0.17424875683266455,
 -0.7675990132102534,
 0.9389313804296981,
 0.3734723161805483,
 0.6347153822370523,
 -0.21087771556795773,
 2.308753722318474,
 0.6009921603717154]

In [9]:
import math

In [41]:
w = list(abs((randn(8)*10)))

In [13]:
w

[4.172589592887834,
 0.47397733893583677,
 9.903146084897184,
 6.611639678578735,
 0.5037416025544387,
 3.6915172300625656,
 7.650305139620049,
 18.553965191310525]

In [38]:
for i in w:
    print(int(i))

4
0
9
6
0
3
7
18


---

---

---

In [15]:
import numpy as np

In [16]:
a = np.array([1,2,4,5,7,8])

In [17]:
a

array([1, 2, 4, 5, 7, 8])

In [18]:
b = np.array([1,3,4,6,True])

In [19]:
b

array([1, 3, 4, 6, 1])

In [20]:
c = np.array([1,3,4,6,"hello"])

In [21]:
c

array(['1', '3', '4', '6', 'hello'], dtype='<U11')

In [22]:
print(c)

['1' '3' '4' '6' 'hello']


In [23]:
c.mean()

TypeError: cannot perform reduce with flexible type

In [24]:
a.sum()

27

In [25]:
a.mean()

4.5

---

In [26]:
 #slicing in array

In [27]:
l = [1,4,64,7,4,45,7,45]

In [28]:
m = np.array(l)

In [29]:
print(m)

[ 1  4 64  7  4 45  7 45]


In [33]:
t = m[::2]
t

array([ 1, 64,  4,  7])

In [35]:
t[:]=0
m

array([ 0,  4,  0,  7,  0, 45,  0, 45])